spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  application:
    name: vkr
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql:${YOUR_URL_TO_DB}
    username: ${USER}
    password: ${PASS}
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
jwt:
  secret: 821930213jdwfgsa72g32v1tgw4edb213123hbxs
  lifetime: 30m